apiVersion: v1
kind: Namespace
metadata:
  name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx-deploy
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - name: nginx-deploy
        image: nginx:latest
        resources:
          requests:
             memory: 512Mi
             cpu: 0.5

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy-svc
  namespace: nginx

spec:

  selector:
    app: nginx-deploy

  ports:
    - name: http
      port: 80

  type: NodePort
